"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Orc = exports.Halfling = exports.Elf = exports.Dwarf = void 0;
const Race_1 = require("./Race");
const Dwarf_1 = require("./Dwarf");
exports.Dwarf = Dwarf_1.default;
const Elf_1 = require("./Elf");
exports.Elf = Elf_1.default;
const Halfling_1 = require("./Halfling");
exports.Halfling = Halfling_1.default;
const Orc_1 = require("./Orc");
exports.Orc = Orc_1.default;
exports.default = Race_1.default;
